### ISSUE TITLE
Comprobación de números primos

### ISSUE THREAD

**Issue by abelardolg** [AleTanuki/listas#1]
Los números primos se hallan a partir del 2; el 0 y el 1 no entra en esta lista. Por lo tanto, la línea 6 sobra.
![image](https://user-images.githubusercontent.com/22522883/155977025-f4a879fc-cce8-43c5-92ec-58c7be6a9e1a.png)

**Comment by AleTanuki** [comment]
cierto,eso pasa por copy paste pero como no estorbaba no lo habia considerado quitarlo

**Comment by abelardolg** [comment]
Está bien copiar y pegar, pero has de hacer un ejercicio de comprensión antes de incorporarlo a la versión definitiva de tu código.
