### ISSUE TITLE
Candidato == 4

### ISSUE THREAD

**Issue by abelardolg** [AleTanuki/listas#2]
¿Por qué de esta comprobación?

**Comment by AleTanuki** [comment]
pq el 4 es especial al parecer,me puse a investigar el como ver si un numero era primo y varias consultas decian lo mismo q es especial

**Comment by abelardolg** [comment]
Tu algoritmo que te indica si un número X es primo o no debería ser capaz de indicar que el 4 no es primo.

**Comment by AleTanuki** [comment]
> Tu algoritmo que te indica si un número X es primo o no debería ser capaz de indicarte que el 4 no es primo.

vi varios ejemplos por google y todos coincidian con lo mismo y tecnicamente te dice la funcion q no es primo

**Comment by abelardolg** [comment]
No hace falta. Puedes borrar la línea y verás que, si le pasas el 4, el algoritmo te dirá que no es primo. Y si te dice que es primo..., es que tu algoritmo está mal.

**Comment by AleTanuki** [comment]
> No hace falta. Puedes borrar la línea y verás que, si le pasas el 4, el algoritmo te dirá que no es primo. Y si te dice que es primo..., es que tu algoritmo está mal.

comprobado sin el if del 4 funciona bien
