### ISSUE TITLE
Primo: ¿Por qué un for?

### ISSUE THREAD

**Issue by abelardolg** [AleTanuki/listas#3]
¿Por qué un for?

**Comment by AleTanuki** [comment]
> ¿Por qué un for?

esa funcion entera la he sacado de google,nunca he llegado a entender como va el obtener primos en programacion

**Comment by abelardolg** [comment]
No solo basta con copiar, también has de entender y comprender el algoritmo.

**Comment by abelardolg** [comment]
El bucle for es finito, al igual que el do...while y el while, pero se usa para determinados casos.
Si una condición se cumple en su bucle, y esta hace que tengas que salir del for, entonces no es un for.
La única condición por la cual debería finalizar un for es la que está en su cabecera.

**Comment by AleTanuki** [comment]
> 

y eso hace,osea cumple su objetivo he hecho pruebas solo con este cacho y no da problemas y cumple

**Comment by abelardolg** [comment]
Este for sale por 3 sitios, y solo debería salir por uno: la condición de su cabecera.
![image](https://user-images.githubusercontent.com/22522883/155981014-ff6ad563-0f27-4f94-9502-c9a27e0399af.png)
