### ISSUE TITLE
Typedef struct Numero

### ISSUE THREAD

**Issue by abelardolg** [AleTanuki/listas#4]
Creo que está mal: ¿por qué solo un número?

**Comment by AleTanuki** [comment]
> Creo que está mal: ¿por qué solo un número?

pq queria primero mirarlo solo con un numero y si me salia bien lo adaptaba al 2º
el numero no primo y despues su divisor

**Comment by abelardolg** [comment]
La incorporación de un segundo campo desde el inicio no afectaba a tus pruebas.

**Comment by AleTanuki** [comment]
> La incorporación de un segundo campo desde el inicio no afectaba a tus pruebas.

preferia hacerlo 1º con una para q si fallaba supiera en q zona

**Comment by abelardolg** [comment]
Te da igual: el número de campos no debería afectar a tus pruebas con ese campo.

**Comment by AleTanuki** [comment]
> Te da igual: el número de campos no debería afectar a tus pruebas con ese campo.

si,si pero si hay un fallo me resulta mas facil con un campo q con 2,q no pasaria nada,no,pero asi trabajo mas comoda
